var sources = []
var sinks = []
var regular = []
var A = []
var B = []
var C = []
var A_highlight = []
var B_highlight = []
var C_highlight = []
var highlight = []

var transitions = []
var places = []
